# Exploratory Data Analysis
This notebook is designed to explore the structure of the DB1B airline data set. We will examine Coupon data from 2011 Q1.

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import signac

# Show more columns so we can see everything
pd.options.display.max_columns = 50

project = signac.get_project()

In [2]:
job = project.find_jobs({"year": 2011, "quarter": 1}).next()
df = pd.read_csv(job.fn('Coupon.csv'))

/home/bdice/miniconda3/envs/dice/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3044: DtypeWarning: Columns (28) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [3]:
df.head()

,ItinID,MktID,SeqNum,Coupons,Year,OriginAirportID,OriginAirportSeqID,OriginCityMarketID,Quarter,Origin,OriginCountry,OriginStateFips,OriginState,OriginStateName,OriginWac,DestAirportID,DestAirportSeqID,DestCityMarketID,Dest,DestCountry,DestStateFips,DestState,DestStateName,DestWac,Break,CouponType,TkCarrier,OpCarrier,RPCarrier,Passengers,FareClass,Distance,DistanceGroup,Gateway,ItinGeoType,CouponGeoType,Unnamed: 36
0,20111716058,2011171605801,1,1,2011,13232,1323201,30977,1,MDW,US,17,IL,Illinois,41,13487,1348701,31650,MSP,US,27,MN,Minnesota,63,X,A,DL,CP,CP,4.0,X,349.0,1,0.0,2,2,NaN
1,20111716059,2011171605901,1,1,2011,13232,1323201,30977,1,MDW,US,17,IL,Illinois,41,13487,1348701,31650,MSP,US,27,MN,Minnesota,63,X,A,DL,CP,CP,2.0,X,349.0,1,0.0,2,2,NaN
2,20111716060,2011171606001,1,1,2011,13232,1323201,30977,1,MDW,US,17,IL,Illinois,41,13487,1348701,31650,MSP,US,27,MN,Minnesota,63,X,A,DL,CP,CP,1.0,X,349.0,1,0.0,2,2,NaN
3,20111716061,2011171606101,1,1,2011,13232,1323201,30977,1,MDW,US,17,IL,Illinois,41,13487,1348701,31650,MSP,US,27,MN,Minnesota,63,X,A,DL,CP,CP,2.0,X,349.0,1,0.0,2,2,NaN
4,20111716062,2011171606201,1,1,2011,13232,1323201,30977,1,MDW,US,17,IL,Illinois,41,13487,1348701,31650,MSP,US,27,MN,Minnesota,63,X,A,DL,CP,CP,1.0,X,349.0,1,0.0,2,2,NaN

In [4]:
df.describe()

,ItinID,MktID,SeqNum,Coupons,Year,OriginAirportID,OriginAirportSeqID,OriginCityMarketID,Quarter,OriginStateFips,OriginWac,DestAirportID,DestAirportSeqID,DestCityMarketID,DestStateFips,DestWac,Passengers,Distance,DistanceGroup,Gateway,ItinGeoType,CouponGeoType,Unnamed: 36
count,8.592669e+06,8.592669e+06,8.592669e+06,8.592669e+06,8592669.0,8.592669e+06,8.592669e+06,8.592669e+06,8592669.0,8.592669e+06,8.592669e+06,8.592669e+06,8.592669e+06,8.592669e+06,8.592669e+06,8.592669e+06,8.592669e+06,8.592669e+06,8.592669e+06,8592669.0,8.592669e+06,8.592669e+06,0.0
mean,1.427545e+11,1.427545e+13,2.133666e+00,3.267331e+00,2011.0,1.264210e+04,1.264211e+06,3.171829e+04,1.0,2.697500e+01,5.423797e+01,1.264163e+04,1.264165e+06,3.171689e+04,2.698798e+01,5.421359e+01,1.571606e+00,8.317542e+02,2.168317e+00,0.0,1.930250e+00,1.957203e+00,NaN
std,8.540562e+10,8.540562e+12,1.141451e+00,1.220601e+00,0.0,1.528474e+03,1.528471e+05,1.320510e+03,0.0,1.666506e+01,2.572562e+01,1.529647e+03,1.529645e+05,1.320331e+03,1.665545e+01,2.573750e+01,4.221053e+00,6.403622e+02,1.297877e+00,0.0,2.547249e-01,2.023983e-01,NaN
min,2.011110e+05,2.011110e+07,1.000000e+00,1.000000e+00,2011.0,1.013500e+04,1.013501e+06,3.000900e+04,1.0,1.000000e+00,1.000000e+00,1.013500e+04,1.013501e+06,3.000900e+04,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+01,1.000000e+00,0.0,1.000000e+00,1.000000e+00,NaN
25%,2.011180e+10,2.011180e+12,1.000000e+00,2.000000e+00,2011.0,1.129200e+04,1.129202e+06,3.056100e+04,1.0,1.200000e+01,3.400000e+01,1.129200e+04,1.129202e+06,3.055900e+04,1.200000e+01,3.400000e+01,1.000000e+00,3.580000e+02,1.000000e+00,0.0,2.000000e+00,2.000000e+00,NaN
50%,2.011116e+11,2.011116e+13,2.000000e+00,4.000000e+00,2011.0,1.288900e+04,1.288902e+06,3.142300e+04,1.0,2.600000e+01,4.400000e+01,1.288900e+04,1.288902e+06,3.129500e+04,2.600000e+01,4.400000e+01,1.000000e+00,6.460000e+02,2.000000e+00,0.0,2.000000e+00,2.000000e+00,NaN
75%,2.011123e+11,2.011123e+13,3.000000e+00,4.000000e+00,2011.0,1.402700e+04,1.402701e+06,3.257500e+04,1.0,4.200000e+01,8.100000e+01,1.405700e+04,1.405701e+06,3.257500e+04,4.200000e+01,8.100000e+01,1.000000e+00,1.086000e+03,3.000000e+00,0.0,2.000000e+00,2.000000e+00,NaN
max,2.011131e+11,2.011131e+13,1.500000e+01,1.500000e+01,2011.0,1.621800e+04,1.621801e+06,3.613300e+04,1.0,7.800000e+01,9.300000e+01,1.621800e+04,1.621801e+06,3.613300e+04,7.800000e+01,9.300000e+01,9.640000e+02,7.446000e+03,1.500000e+01,0.0,2.000000e+00,2.000000e+00,NaN

In [5]:
df = df.drop(columns=['Gateway', 'Unnamed: 36'])

In [6]:
df.dtypes

ItinID                  int64
MktID                   int64
SeqNum                  int64
Coupons                 int64
Year                    int64
OriginAirportID         int64
OriginAirportSeqID      int64
OriginCityMarketID      int64
Quarter                 int64
Origin                 object
OriginCountry          object
OriginStateFips         int64
OriginState            object
OriginStateName        object
OriginWac               int64
DestAirportID           int64
DestAirportSeqID        int64
DestCityMarketID        int64
Dest                   object
DestCountry            object
DestStateFips           int64
DestState              object
DestStateName          object
DestWac                 int64
Break                  object
CouponType             object
TkCarrier              object
OpCarrier              object
RPCarrier              object
Passengers            float64
FareClass              object
Distance              float64
DistanceGroup           int64
ItinGeoType             int64
CouponGeoType           int64
dtype: object

In [7]:
for col, dtype in df.dtypes.items():
    if dtype == np.int64:
        df[col] = pd.to_numeric(df[col], downcast='integer')
    elif dtype == np.float64:
        df[col] = pd.to_numeric(df[col], downcast='float')

In [8]:
dict(df.dtypes)

{'ItinID': dtype('int64'),
 'MktID': dtype('int64'),
 'SeqNum': dtype('int8'),
 'Coupons': dtype('int8'),
 'Year': dtype('int16'),
 'OriginAirportID': dtype('int16'),
 'OriginAirportSeqID': dtype('int32'),
 'OriginCityMarketID': dtype('int32'),
 'Quarter': dtype('int8'),
 'Origin': dtype('O'),
 'OriginCountry': dtype('O'),
 'OriginStateFips': dtype('int8'),
 'OriginState': dtype('O'),
 'OriginStateName': dtype('O'),
 'OriginWac': dtype('int8'),
 'DestAirportID': dtype('int16'),
 'DestAirportSeqID': dtype('int32'),
 'DestCityMarketID': dtype('int32'),
 'Dest': dtype('O'),
 'DestCountry': dtype('O'),
 'DestStateFips': dtype('int8'),
 'DestState': dtype('O'),
 'DestStateName': dtype('O'),
 'DestWac': dtype('int8'),
 'Break': dtype('O'),
 'CouponType': dtype('O'),
 'TkCarrier': dtype('O'),
 'OpCarrier': dtype('O'),
 'RPCarrier': dtype('O'),
 'Passengers': dtype('float32'),
 'FareClass': dtype('O'),
 'Distance': dtype('float32'),
 'DistanceGroup': dtype('int8'),
 'ItinGeoType': dtype('int8'),
 'CouponGeoType': dtype('int8')}

In [9]:
# Use these dtypes in the future when reading with pandas, and drop any columns not in this list
dtypes = {
    'ItinID': np.int64,
    'MktID': np.int64,
    'SeqNum': np.int8,
    'Coupons': np.int8,
    'Year': np.int16,
    'OriginAirportID': np.int16,
    'OriginAirportSeqID': np.int32,
    'OriginCityMarketID': np.int32,
    'Quarter': np.int8,
    'Origin': str,
    'OriginCountry': str,
    'OriginStateFips': np.int8,
    'OriginState': str,
    'OriginStateName': str,
    'OriginWac': np.int8,
    'DestAirportID': np.int16,
    'DestAirportSeqID': np.int32,
    'DestCityMarketID': np.int32,
    'Dest': str,
    'DestCountry': str,
    'DestStateFips': np.int8,
    'DestState': str,
    'DestStateName': str,
    'DestWac': np.int8,
    'Break': str,
    'CouponType': str,
    'TkCarrier': str,
    'OpCarrier': str,
    'RPCarrier': str,
    'Passengers': np.float32,
    'FareClass': str,
    'Distance': np.float32,
    'DistanceGroup': np.int8,
    'ItinGeoType': np.int8,
    'CouponGeoType': np.int8}

In [10]:
df['Origin'].unique()

array(['MDW', 'MEM', 'MHT', 'MKE', 'MOT', 'MSN', 'MSO', 'MSP', 'MSY',
       'MWA', 'MYR', 'OMA', 'ORD', 'ORF', 'PHL', 'PIT', 'PVD', 'PWM',
       'RDU', 'RIC', 'ROC', 'SAT', 'SBN', 'SDF', 'STL', 'SYR', 'TYS',
       'ABQ', 'ALB', 'ANC', 'ART', 'ATL', 'AUG', 'AUS', 'AVL', 'BDL',
       'BGR', 'BHM', 'BIL', 'BIS', 'BNA', 'BOI', 'BOS', 'BTV', 'BUF',
       'BWI', 'BZN', 'CAE', 'CGI', 'CHS', 'CLE', 'CLT', 'CMH', 'COS',
       'CVG', 'DAB', 'DAY', 'DCA', 'DEN', 'DFW', 'DLH', 'DTW', 'ECP',
       'EGE', 'ELP', 'ERI', 'EUG', 'EVV', 'EWR', 'EYW', 'FAR', 'FCA',
       'FLL', 'FNT', 'FSD', 'FWA', 'GEG', 'GFK', 'GPT', 'GRB', 'GRR',
       'GSO', 'GSP', 'HDN', 'HGR', 'HNL', 'HOU', 'HSV', 'IAD', 'IAH',
       'IND', 'IRK', 'JAC', 'JAN', 'JAX', 'JFK', 'KOA', 'LAS', 'LAX',
       'LEB', 'LEX', 'LGA', 'LIH', 'LIT', 'LNS', 'LNY', 'MAZ', 'MCI',
       'MCN', 'MCO', 'MIA', 'MLB', 'MSS', 'MTJ', 'MVY', 'OAK', 'OGG',
       'OGS', 'OKC', 'ONT', 'PBI', 'PDX', 'PHF', 'PHX', 'PNS', 'PSE',
       'PSP', 'RAP', 'RKD', 'RNO', 'RSW', 'RUT', 'SAN', 'SAV', 'SEA',
       'SFO', 'SJC', 'SJU', 'SLC', 'SLK', 'SMF', 'SNA', 'SRQ', 'STT',
       'STX', 'SUN', 'TBN', 'TLH', 'TPA', 'TUL', 'TUS', 'UIN', 'VPS',
       'VQS', 'ABE', 'ABY', 'AEX', 'AGS', 'ATW', 'BMI', 'BQK', 'BTR',
       'CAK', 'CHA', 'CHO', 'CID', 'CRW', 'CSG', 'DHN', 'DSM', 'ELM',
       'EWN', 'FAY', 'FLO', 'GNV', 'GRK', 'GTR', 'HPN', 'ICT', 'ILM',
       'LFT', 'LWB', 'LYH', 'MDT', 'MEI', 'MFE', 'MGM', 'MLI', 'MLU',
       'MOB', 'OAJ', 'ROA', 'SGF', 'SHV', 'SWF', 'TRI', 'VLD', 'XNA',
       'PIE', 'ACY', 'BKG', 'UTM', 'AZA', 'BFL', 'BLI', 'CPR', 'FAT',
       'FNL', 'GJT', 'GRI', 'GTF', 'HTS', 'IDA', 'LGB', 'LRD', 'MFR',
       'MRY', 'OWB', 'PBG', 'PGD', 'PIA', 'PSC', 'PUB', 'RDM', 'RFD',
       'SCK', 'SFB', 'SMX', 'TOL', 'TWF', 'YNG', 'BFF', 'CEZ', 'CNY',
       'CYS', 'DDC', 'DIK', 'EAR', 'FMN', 'GCC', 'GCK', 'ISN', 'JLN',
       'LAR', 'LBL', 'MCK', 'RIW', 'RKS', 'SHR', 'VEL', 'ITO', 'JHM',
       'MKK', 'PPG', 'ASE', 'DRO', 'ABI', 'ACT', 'AMA', 'BQN', 'BUR',
       'HYS', 'SPN', 'GUM', 'GUC', 'PIR', 'SBP', 'AVP', 'YUM', 'FLG',
       'SBA', 'TEX', 'SBY', 'HVN', 'ISP', 'ITH', 'BGM', 'SCE', 'HHH',
       'PGV', 'IPT', 'MBL', 'AZO', 'CWA', 'LAN', 'LSE', 'MQT', 'RST',
       'IMT', 'COU', 'LBB', 'BRO', 'ABR', 'ATY', 'HLN', 'INL', 'MCW',
       'SUX', 'PIB', 'MBS', 'TVC', 'ALO', 'LNK', 'PLN', 'CIU', 'DAL',
       'FSM', 'BJI', 'ESC', 'APN', 'FOD', 'HIB', 'JMS', 'RHI', 'TUP',
       'DVL', 'GLH', 'MSL', 'BRD', 'MAF', 'CRP', 'PQI', 'CLL', 'LCH',
       'JST', 'MGW', 'EAU', 'SPI', 'BPT', 'VCT', 'SHD', 'CKB', 'TYR',
       'HRL', 'DRT', 'DUJ', 'AOO', 'BHB', 'GGG', 'LAW', 'MHK', 'ROW',
       'SJT', 'SPS', 'TXK', 'SAF', 'CMI', 'MMH', 'RDD', 'DBQ', 'CLD',
       'YKM', 'ACV', 'LMT', 'EAT', 'FAI', 'JNU', 'STS', 'CIC', 'MOD',
       'EKO', 'LWS', 'SGU', 'PAH', 'CMX', 'OTH', 'ALW', 'AKN', 'BET',
       'ENA', 'OTZ', 'SIT', 'OME', 'SNP', 'CYF', 'SCC', 'BRW', 'KTN',
       'PSG', 'WRG', 'YAK', 'PUW', 'VDZ', 'DLG', 'HOM', 'KSM', 'ADQ',
       'CDV', 'CDB', 'DUT', 'MCG', 'SDP', 'ILE', 'ACK', 'HYA', 'PVC',
       'GBD', 'JHW', 'PKB', 'COD', 'WRL', 'BFD', 'LBF', 'IPL', 'FKL',
       'MKG', 'TVF', 'BTM', 'PIH', 'CDC', 'IYK', 'CEC', 'MKL', 'PGA',
       'SOW', 'ALM', 'CNM', 'CVN', 'BKW', 'IGM', 'ALS', 'ADK', 'PRC',
       'SDY', 'GGW', 'HVR', 'OLF', 'AHN', 'VIS', 'HON', 'MCE', 'IWD',
       'EWB', 'IAG', 'LBE', 'CDR', 'MLS', 'SVC', 'IFP', 'LCK', 'AIA',
       'BRL', 'GDV', 'ANI', 'UNK', 'ELD'], dtype=object)

We should extract information about unique origins and destinations. See next notebook.